### ISSUE TITLE
Issacgym simulation environment

### ISSUE THREAD

**Issue by hahahalove57** [robocasa/robocasa#100]
Thanks for your great contribution！ I want to load RoboCasa scenes in the simulation environment of IssacGym. Is this possible? Is it troublesome to change from Mujoco to IssacGym?

**Comment by snasiriany** [comment]
IsaacGym is now deprecated and now IsaacLab appears to be the recommended software. I think converting from MuJoCo (and specifically RoboCasa) to IsaacLab is quite an involved process, but here are some resources that may helpful:
* MJCF importer: https://docs.omniverse.nvidia.com/isaacsim/latest/features/environment_setup/ext_omni_isaac_mjcf.html
* RoboSuite's [USD exporter](https://robosuite.ai/docs/demos.html#exporting-to-usd) which allows for rendering in Omniverse (but no physics integration with Isaac Labs directly)
