### ISSUE TITLE
Availability of the demonstration datasets

### ISSUE THREAD

**Issue by kailucs** [robocasa/robocasa#105]
Hi, thanks for contributing the great dataset for kitchen robots. 

I noticed that in the paper there are 20 composite tasks (multi-stage tasks), but after downloading, there are only 5 of them provided. 

I am wondering whether other multi-stage tasks' demonstrations are available? Thank you in advance!

**Comment by snasiriany** [comment]
Thanks for the question. We actually have about ~75 composite tasks, listed here: https://robocasa.ai/docs/tasks_scenes_assets/composite_tasks.html

In this latest iteration of RoboCasa, we have collected data for 5 of these composite tasks. We are working on collecting demos for more tasks and releasing MimicGen data for them as well, but the timeline for that is a ways off.

I hope this is helpful!
