### ISSUE TITLE
Negative value for loss

### ISSUE THREAD

**Issue by xiaohao9999** [robocasa/robocasa#106]
Hi,

When I run the train code, the loss appears as follows:

![image](https://github.com/user-attachments/assets/322edb88-0324-415c-8aeb-7a4d6f0abf92)

I just modified the ‘data’ in the json file and kept only one task ‘PnPCounterToCab’ for training. What's going on here?

**Comment by snasiriany** [comment]
This is logging the negative log likelihood. It appear to work as expected. Can you share more details about the concern?

**Comment by xiaohao9999** [comment]
Yes, I was mistaken. Thank you for your prompt reply!
