### ISSUE TITLE
Details of state space and action space of demo tasks

### ISSUE THREAD

**Issue by AmoghJuloori** [robocasa/robocasa#11]
Hi, the RoboCasa dataset is quite interesting and I enjoyed running the tasks. Thanks for sharing this work! 
I ran the task 5: Close Drawer and found the shape of states as: (236,166) for demo_9. 
![robocasa_demo](https://github.com/robocasa/robocasa/assets/97470922/d5b44c58-539f-4237-b556-561cbbaf5dc1)
Here is the video of the specified run:
https://drive.google.com/file/d/1k5KE8cmw_piFdOxpVqMx0i0sv05hGUbm/view?usp=sharing
I understand that it is in the format : (length of trajectory, number of observations in a state)

I have few questions related to the state space and action space of the demo tasks:
1. The shape of states - Not only the trajectory length, but the number of observations also change with the demo run. I would like to understand what this ‘166’ consists of - only proprioception data of the manipulator or if the states of objects in the environment are also included? 
2. Do these observations also include visual (image based) data?
3. What does the action space consist of?

I would like to know these details about the tasks as it will be helpful in studying how the demo tasks work.

**Comment by snasiriany** [comment]
Hi @AmoghJuloori thanks for these great questions. Here are some more details:
1. I believe the state you are referring to here is the low dimensional MuJoCo state, that captures all of the degrees of freedom in the environment. It may change depending on the number of fixtures, the number of objects currently in the environment.
2. We offer [images](https://github.com/ARISE-Initiative/robomimic/blob/2e32a25f9aea6ba486de39e1d8d353244fe8a039/robomimic/scripts/config_gen/helper.py#L177-L179) and low-dimensional [proprioception states](https://github.com/ARISE-Initiative/robomimic/blob/2e32a25f9aea6ba486de39e1d8d353244fe8a039/robomimic/scripts/config_gen/helper.py#L165-L169) in our demos. You may want to consider using these observation keys (located under the "obs" group of each demo).
3. By default, the action space consists of the elements controlling for the arm (Cartesian control), followed by elements controlling the gripper, followed by elements controlling the base, followed by one (binary) element controlling whether to control the arm or base.
