### ISSUE TITLE
Behavior cloning training scripts?

### ISSUE THREAD

**Issue by cheryyunl** [robocasa/robocasa#12]
Hi there,

We plan to use Robocasa as an experimental domain for our paper. However, we're concerned that our current behavior cloning (BC) training script might not align perfectly with the Robocasa benchmark requirements.

Would you consider releasing your BC training code? Having it as a reference would be immensely helpful for us to ensure compatibility and achieve the best possible results with Robocasa.

Thanks in advance for your time and consideration!

**Comment by snasiriany** [comment]
Please see our policy learning repo! https://github.com/ARISE-Initiative/robomimic/tree/robocasa

Note, this repo is experimental, and we are still in the process of uploading all of our MimicGen datasets.

**Comment by luccachiang** [comment]
Hi @snasiriany , would you please check this issue? It seems that there is something wrong with the policy learning repo. Thanks! https://github.com/ARISE-Initiative/robomimic/issues/159

**Comment by snasiriany** [comment]
Yes! Following up in that thread
