### ISSUE TITLE
Do you have any plans to support the Stretch 3 robot?

### ISSUE THREAD

**Issue by GuanxingLu** [robocasa/robocasa#13]
Great work! Do you have any plans to support the Stretch 3 robot (https://hello-robot.com/stretch-3-product)? Or could you share any advice on incorporating your repository with Stretch 3 (3D models, action spaces, ..., etc.)?

**Comment by snasiriany** [comment]
Hi! We may do so for the next version of the release! In the meanwhile, if you're interested in incorporating it, here are the steps:
1. Obtain raw assets (MuJoCo menageries offers stretch 2 [here](https://github.com/google-deepmind/mujoco_menagerie/tree/main/hello_robot_stretch))
2. Add the assets to [this folder](https://github.com/ARISE-Initiative/robosuite/tree/robocasa_v0.1/robosuite/models/assets/robots). Follow the example for google robot [here](https://github.com/ARISE-Initiative/robosuite/blob/robocasa_v0.1/robosuite/models/assets/robots/google_robot/robot.xml) for the model conventions.
3. Create a class for the stretch robot in [this folder](https://github.com/ARISE-Initiative/robosuite/tree/robocasa_v0.1/robosuite/models/robots/manipulators). Then register the class [here](https://github.com/ARISE-Initiative/robosuite/blob/robocasa_v0.1/robosuite/models/robots/manipulators/__init__.py).
