### ISSUE TITLE
Question about Robocasa setup running on Windows

### ISSUE THREAD

**Issue by Lexieqiqi** [robocasa/robocasa#15]
"RuntimeError: invalid value for environment variable MUJOCO_GL: egl"
![image](https://github.com/robocasa/robocasa/assets/34876411/cb01edb3-40c4-4128-aba4-add7e3d31b1a)

![屏幕截图 2024-06-09 174746](https://github.com/robocasa/robocasa/assets/34876411/a9f1eac9-868d-40f4-88ad-c506302a5d80)

**Comment by snasiriany** [comment]
There was a [comment here](https://github.com/ARISE-Initiative/robosuite/issues/323#issuecomment-1707864112) that might be helpful. Can you try this and let us know if it resolves the issue?

**Comment by yukezhu** [comment]
@Lexieqiqi please let us know if this issue is resolved. We will close this issue in a week if there's no response. Thanks!
