### ISSUE TITLE
Bathroom & Toilet environments please

### ISSUE THREAD

**Issue by ramkumarkoppu** [robocasa/robocasa#17]
Hi,

Is it possible to get dataset of typical houses bathroom and toilets environment datasets to use it with the robocasa to use it the simulation for robot policy learning and evalution?

**Comment by snasiriany** [comment]
Thanks for sharing this suggestion! A similar question was asked before here, and we offer some context in our response: https://github.com/robocasa/robocasa/issues/9

Support for additional types of scenes is something that's on our longer-term radar. We are considering this for future releases!
