### ISSUE TITLE
Loading multi-stage tasks

### ISSUE THREAD

**Issue by vantony1** [robocasa/robocasa#19]
Hi,

I am trying to load the multi-stage, composite tasks that have been described in your system however looking at the robot teleop code, it is unclear to me how to do so after reading the demo codes and reading the environment/kitchen/multistage files. 

https://github.com/robocasa/robocasa/blob/2918ef92925d5ac8a7baf57f9b0186c2049f48fb/robocasa/demos/demo_teleop.py#L93
This line seems to suggest that environment is linked directly to a task however to me it seems the multistage tasks are encoded as a set of separate single stage task files. I am having trouble figuring out how to simulate a multi-stage task.

Could you please point me in the right direction?

**Comment by snasiriany** [comment]
All of the multi-stage tasks are under the `robocasa/environments/kitchen/multi_stage` folder. Under the `multi_stage` folder, there are 20 folders, each corresponding to a different type of activity. Then under each activity folder, there are the tasks associated with that activity, and the name of the task to pass to `args.task` is the class name of the task, eg. `BreadSetupSlicing` [here](https://github.com/robocasa/robocasa/blob/1370b9e0f747d84fb21ed29bacefb1654865301b/robocasa/environments/kitchen/multi_stage/chopping_food/bread_setup_slicing.py#L4).

Hope this explains the structure!
