### ISSUE TITLE
error after downloading "PnPCounterToicrowave" 

### ISSUE THREAD

**Issue by fortyMiles** [robocasa/robocasa#20]
Hi, thanks for your contribution on this environment. 

Recently, I try to install and run the training examples. I met an error " /home/username/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToMicrowave/2024-04-27/demo_gentex_im128_randcams.hdf5
run failed with error:
Unable to open file (file signature not found)" 

with   

File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
--- 

I have tried to re-download and overwrite several times of **PnPCounterToMicrowave** data. But this issue still exists. 

Can you help me to solve that? 

Best Regards! 

<img width="1590" alt="image" src="https://github.com/ARISE-Initiative/robomimic/assets/6982171/001117ec-7a9b-42e0-a5fa-54eafee78922">

**Comment by snasiriany** [comment]
Thanks for raising the issue! There was an incorrect URL link for this specific dataset. I just updated the link in the code. Please pull the latest changes are run:

```
python -m robocasa.scripts.download_datasets --tasks PnPCounterToMicrowave --overwrite
```
