### ISSUE TITLE
a question about action space 

### ISSUE THREAD

**Issue by mrvgao** [robocasa/robocasa#24]
Hello, @snasiriany 

Thanks for your previous help. 

I can run robomimic successfully after your guidance. After I train the model, I want to explore the mechanism of policies' outputs. 

I want to find out how to "actions" apply robots kinematics but failed. 

Would you please give some information or source code citations that I can loop these things up? 

Thank you very much.

**Comment by snasiriany** [comment]
Apologies for the delayed response! By default, for the datasets we provide, the action space consists of the elements controlling for the arm (Cartesian control, 6 dof), followed by elements controlling the gripper (1 dof), followed by elements controlling the base (4 dof), followed by one (binary) element controlling whether to control the arm or base (1 dof). So 12 dimensions total.

**Comment by abhishek47kashyap** [comment]
> controlling the base (4 dof)

It's a bit unclear what do those 4 DOF stand for. Could you please clarify? If they were 3 I might have guessed `(x, y, yaw)` but the extra 4th dimension is throwing me off.
