### ISSUE TITLE
Questions about supporting Custom Robot Embodiments?

### ISSUE THREAD

**Issue by return-sleep** [robocasa/robocasa#26]
Thanks for your excellent work! I appreciate the diversity of robot embodiments currently supported by your simulator, as shown on your website. I’m interested in exploring whether it’s possible to use custom robot physical models, not currently listed, for data generation on your simulation platform.

Could you guide whether user-provided models are supported and, if so, how we might integrate them?

**Comment by snasiriany** [comment]
Hi! There was a similar thread on this here: https://github.com/robocasa/robocasa/issues/13
I give a brief explanation for supporting new robot models there.
We are also working on some documentation right now, and we can provide more details on the process of integrating new models.
