### ISSUE TITLE
Objaverse object processing

### ISSUE THREAD

**Issue by JasonMa2016** [robocasa/robocasa#28]
Hi Soroush,

Great work! I wonder whether you could release the code for processing all the Objaverse objects into Mujoco MJCF xml format? Thanks!

**Comment by abhihjoshi** [comment]
Hi @JasonMa2016, maybe this might be helpful? https://github.com/kevinzakka/obj2mjcf

**Comment by snasiriany** [comment]
Echoing Abhishek's response, our object import pipeline is largely built on top of obj2mjcf. So we will defer people interested in this feature to that repo. Thanks!
