### ISSUE TITLE
Issue about Oracle Engine

### ISSUE THREAD

**Issue by LongXinKou** [robocasa/robocasa#35]
Hello,

I would like to inquire if your project includes a built-in low-level Oracle engine. Specifically, I would like to know if such an engine can support collecting high-quality data, especially for video and language descriptions.

Thank you so much!

**Comment by snasiriany** [comment]
Hi! We do generate trajectories with MimicGen, but we have not released the data generation code from MimicGen yet. That is on our roadmap. Feel free to open up the issue again if you have additional questions or feedback!
