### ISSUE TITLE
File structure of robocasa and robomimic

### ISSUE THREAD

**Issue by eric-li-2** [robocasa/robocasa#36]
Hi, I followed the instructions downloading the policy learning repo after downloading robocasa. But this resulted in the robomimic folder being nested inside the robocasa folder. Is this intentional? 

Here is the current file structure:
```
robocasa
  robocasa 
  robomimic
    robomimic
    ...
```

**Comment by abhihjoshi** [comment]
I believe the Robomimic repo can be cloned outside the Robocasa repo. The file structure should look something like this:
```
robocasa
|--- robocasa
|--- ...
robomimic
|--- robomimic
|--- ...
```
