### ISSUE TITLE
Data Generation with MimicGen

### ISSUE THREAD

**Issue by Guiliang** [robocasa/robocasa#40]
Hi,

Is there a plan to release the data generation script based on MimicGen? Additionally, if we generate data directly using [MimicGen](https://mimicgen.github.io/), can we achieve performance that aligns with the results reported in the paper?

**Comment by snasiriany** [comment]
We will be releasing our MimicGen datasets shortly. The generation scripts will also come later, most likely towards the end of summer, after we do some cleanup and consolidate the changes with the MimicGen development team.

**Comment by ZzZZCHS** [comment]
Hi @snasiriany,

I noticed that MimicGen released their generation code last month. Could I use that code directly for the RoboCasa dataset, or do you plan to release specific generation code or instructions for RoboCasa?

Thank you!

**Comment by snasiriany** [comment]
@ZzZZCHS We will need to release some specific data generation code that defines all of the stages and objects to track. It's still in progress. Please stay tuned for a few more weeks as we iron out a few things. In the meanwhile, the datasets we already generated are already released.

**Comment by snasiriany** [comment]
fyi: mimicgen support now added, please see here: https://github.com/robocasa/robocasa/issues/108
