### ISSUE TITLE
Training config for generated data

### ISSUE THREAD

**Issue by ZzZZCHS** [robocasa/robocasa#44]
Hello,

Thank you for your excellent work and effort in releasing the code and data.

I noticed that you've released the MimicGen generated data (mg-3000). Using the default config (`epoch_every_n_steps=500` and `batch_size=16`), it would take several epochs to iterate over all the generated data once. I would like to confirm if the training config used for the generated data is the same as that used for the human data?

**Comment by snasiriany** [comment]
Hi @ZzZZCHS yes the training config is the same. We give these policies plenty of epochs to train so that they converge. For simplicity we used the same configs across human and mg, however you can also explore reducing the number of training epochs for the human datasets.
