### ISSUE TITLE
Release of additional demonstration data

### ISSUE THREAD

**Issue by sunwookim1214** [robocasa/robocasa#47]
Hello, I'm trying to use the RoboCasa framework for my paper on scene graph change detection (I plan to submit to this year's RA-L).

I noticed there were only 5 composite task datasets available and I was wondering if you could release additional task datasets. If you could, I would also appreciate it if I could know the composition of the existing and to-be released dataset's kitchen layout and styles. 

Thank you! I appreciate it.

**Comment by snasiriany** [comment]
We do intend to release additional demonstration datasets, but the timeline is uncertain and may take up to a few months. Thank you for your patience!
