### ISSUE TITLE
KeyError: 'objaverse'

### ISSUE THREAD

**Issue by lorandcheng** [robocasa/robocasa#50]
I believe the dict indexing on lines 1625 and 1626 of the function `sample_kitchen_object_helper` in `robocasa/models/objects/kitchen_objects.py` is backwards.

They should be `OBJ_CATEGORIES[cand_cat][reg]` instead of `OBJ_CATEGORIES[reg][cand_cat]`

**Comment by snasiriany** [comment]
great catch! fixed. thank you!
