### ISSUE TITLE
Is it possible to achieve a pick-navigation-place policy?

### ISSUE THREAD

**Issue by PuzhenYuan** [robocasa/robocasa#52]
Hi there! Sorry for raising some of my confusion.
I found that in the task 'pick and place', there are machine-generated and human datasets. Meanwhile in the task 'navigation', there are only human datasets.
However, there are no released datasets for 'pick-navigation-place', which means the robot trained on the datasets above can't directly pick some items from the sink to the microwave which is far from the sink.
Can you give me some advice for handling such tasks? 
And is there any interface to add some codes for planning to solve this problem？
Any kind suggestions or help is appreciated!

**Comment by snasiriany** [comment]
Our MimicGen pipeline does not yet support navigation. Therefore all of the MimicGen datasets we have released thus far concern only manipulation. We are going to support this eventually but it will take some time. In the meanwhile if you develop some kind of navigation planner would like to contribute the code let us know. Thanks!
