### ISSUE TITLE
an issue about the xml code

### ISSUE THREAD

**Issue by hahahalove57** [robocasa/robocasa#54]
Hello! Thank you very much for the excellent environment! For objects in assets/fixtures, is the corresponding xml code generated via obj2mjcf based on the object's obj file? How are the corresponding object's exterior bbox and interior bbox generated in the xml code? After using obj2mjcf, I found that the corresponding xml format can not be directly applied to robocasa, but need to be modified? Did you modify any code based on obj2mjcf to get the fixed format? If so, I hope you can provide the relevant content

**Comment by snasiriany** [comment]
Hi @hahahalove57 the code we used to generate these assets is part of a separate repo and it is not production ready at the moment to release to public. We may do that but at a later date. If you'd like access feel free to email me and I can try to share some relevant code.
