### ISSUE TITLE
RoboCasa in Isaac Sim

### ISSUE THREAD

**Issue by LinJianjie** [robocasa/robocasa#62]
"Robocase is mentioned by NVIDIA as something that can be used in Isaac Sim, according to [this article](https://nvidianews.nvidia.com/news/nvidia-accelerates-worldwide-humanoid-robotics-development). I find it interesting and would like to see how I can use it in Isaac Sim. Do you have any demos for that? Thank you for answering me.

**Comment by snasiriany** [comment]
Thanks, a similar question was asked recently: https://github.com/robocasa/robocasa/issues/58
Please refer to that thread.
