### ISSUE TITLE
Tuning camera in robocasa

### ISSUE THREAD

**Issue by sunwookim1214** [robocasa/robocasa#66]
Is there a way to move the camera around while playing the provided demonstrations?

**Comment by Abhiram824** [comment]
If you press the `esc` key while playing back demonstrations the camera will changed to a free, moveable camera.

**Comment by snasiriany** [comment]
the solution @Abhiram824 mentioned is best right now. feel free to re-open the issue if you have followup questions.

**Comment by sunwookim1214** [comment]
Thank you for your reply. 

Is there a way to query the extrinsic matrix of the movable view?

**Comment by snasiriany** [comment]
Check out this thread, it might be helpful: https://github.com/google-deepmind/dm_control/issues/71
