### ISSUE TITLE
Customizing Object

### ISSUE THREAD

**Issue by ziyi105** [robocasa/robocasa#68]
Thanks for your amazing work! 

I am trying to customize a chair object that is movable, but I am not sure how to do it. Could you please give me some tips on how to do it? Specifically, how does the code load objects from Objaverse and how can I specify a path to a chair object from Objaverse in the code. 

I tried to back-trace the demo_objects function but unfortunately it could not display properly on my laptop, below is a screenshot of what I see when I run the command. This issue persists even if I press N to view another object.

![image](https://github.com/user-attachments/assets/648a4bb6-600f-4979-b2a0-fefd9c12e076)

**Comment by snasiriany** [comment]
Hi @ziyi105,

Are you trying to import a new model from Objaverse into RoboCasa? Or is this an existing chair that we provided already?

For importing new objects, there's a process which involves processing the raw files into submeshes, generating bounding boxes, etc. We based the code for this off of and adapted it for our purposes: https://github.com/kevinzakka/obj2mjcf. Our object import code is not public at this moment.

We do provide some references to existing stools under `robocasa/models/assets/fixtures/accessories/stools` which you can access after you run the initial script to download all the assets (`python robocasa/scripts/download_kitchen_assets.py`)

**Comment by ziyi105** [comment]
Thanks for your reply! 

Is there a way to fix the problem where demo object cannot be shown properly like the in screenshot I provided?

**Comment by snasiriany** [comment]
Can you share additional details on what script you ran exactly, and the computing platform, OS version, mujoco version, whether GPU is used, etc?

**Comment by quas-modo** [comment]
> Hi @ziyi105,
> 
> Are you trying to import a new model from Objaverse into RoboCasa? Or is this an existing chair that we provided already?
> 
> For importing new objects, there's a process which involves processing the raw files into submeshes, generating bounding boxes, etc. We based the code for this off of and adapted it for our purposes: https://github.com/kevinzakka/obj2mjcf. Our object import code is not public at this moment.
> 
> We do provide some references to existing stools under `robocasa/models/assets/fixtures/accessories/stools` which you can access after you run the initial script to download all the assets (`python robocasa/scripts/download_kitchen_assets.py`)

Hi,

I’m in the process of customizing new objects, and I noticed that you mentioned using **obj2mjcf** for this purpose. Could you kindly share which specific parameters or options you’ve used with obj2mjcf during the process? Any insights would be greatly appreciated.

**Comment by ziyi105** [comment]
hi @quas-modo 
I did not end up using obj2mjcf in the end as the object i needed is available in fixture accessories (stool), hence i edited the xml file of stool fixture and add it to kitchen_objects.py

**Comment by ziyi105** [comment]
> Can you share additional details on what script you ran exactly, and the computing platform, OS version, mujoco version, whether GPU is used, etc?

@snasiriany  Sorry I missed your reply. I ran demo_objects.py on windows 11 and no GPU is used. Mujoco verison is 3.1.1

**Comment by snasiriany** [comment]
@ziyi105 do the other demos scripts work for you?

See here: https://robocasa.ai/docs/introduction/quick_start.html

**Comment by ziyi105** [comment]
> @ziyi105 do the other demos scripts work for you?
> 
> See here: https://robocasa.ai/docs/introduction/quick_start.html

Yeah, other demo scripts worked for me, only demo_objects.py didnt work

**Comment by snasiriany** [comment]
Another manual option to try, run `python -m mujoco.viewer --mjcf <path-to-object-xml-file>`

Eg. the xml path can be `robocasa/models/assets/objects/objaverse/boxed_drink/boxed_drink_2/model.xml`

**Comment by ThisisXXZ** [comment]
> [@snasiriany](https://github.com/snasiriany) Hi, I am trying to use obj2mjcf and I noticed robocasa follows robosuite robosuite's xml structure to import objects. The question is how I can get the bottom_site, top_site and horizontal_radius_site for custom objects. Many thanks!

Same problem here. May I ask if you've came up with a solution on that? Really have no idea how to get these three attributes
