### ISSUE TITLE
Difference between Objaverse and Luma.ai generated assets?

### ISSUE THREAD

**Issue by YandanYang** [robocasa/robocasa#69]
Hi, I have loaded the assets. 
Both of the objaverse and luma.ai dataset is good. 
May I ask what is the difference of these two assets? 
Why do you choose two datasets rather than either of them?

By the way, do you apply any data processing of objaverse assets to get the .obj file?
And do you manually adjust the asset's pose to make it uniform, such as the apples in the same pose?

In this image, the left is `aigen_objs`, the  right is `objaverse`.
![image](https://github.com/user-attachments/assets/927a5607-df71-4741-9010-51501b5a8fde)

**Comment by snasiriany** [comment]
Hi @YandanYang 
objaverse assets were manually created by artists, while luma.ai assets are AI-generated from Luma's text-to-3d service.
In general, objaverse assets are slightly higher quality, but luma.ai assets are more diverse (they span more object categories). 

You can see the full list of object categories here: https://github.com/robocasa/robocasa/blob/main/robocasa/models/objects/kitchen_objects.py

We apply data processing to both objaverse and luma.ai assets to segment them and model their collision meshes. The code for that is not publicly available yet, but its based and adapted from Kevin Zakka's obj2mjcf: https://github.com/kevinzakka/obj2mjcf

We also manually adjust the pose of each object to match a canonical pose.
