### ISSUE TITLE
Meaning of 'object' in 'obs'

### ISSUE THREAD

**Issue by JediWarriorZou** [robocasa/robocasa#73]
Hello. In demo data file like xxx.hdf5. The obs has observation categories from 'object' to 'robot0_joint_vel'. I wonder the specific meaning of 'object' which has a (T,42) dimension. Does it mean some position information of an object? Thanks.

**Comment by snasiriany** [comment]
`object` is referring to the pose information about all of the relevant objects in the task, and these elements are concatenated into across all the objects a single vector. See here for how we enumerate over the objects: https://github.com/robocasa/robocasa/blob/daf2fb87ce49c3c83e1d9941b51af5e3c7fe5d42/robocasa/environments/kitchen/kitchen.py#L1117-L1124

For each object, we are storing information about the absolute poses of objects and their relative poses to the end effector, see here: https://github.com/robocasa/robocasa/blob/daf2fb87ce49c3c83e1d9941b51af5e3c7fe5d42/robocasa/environments/kitchen/kitchen.py#L1199-L1204
