### ISSUE TITLE
robosuite __init__.py file imports not running

### ISSUE THREAD

**Issue by eric-li-2** [robocasa/robocasa#75]
I installed robocasa and it was working the first time I installed it.
After shutting down the server and restarting, I tried running the demo tasks scripts a second time but this failed. The code errored when trying to make a robosuite environment "AttributeError: module robosuite has no attribute make" when calling robosuite.make(...)

I am assuming the __init__.py file imports of robosuite are not working as intended. Here is also an error log that appeared when I ran "pip install -e ." for robocasa. I am not sure if it is relevant but I have included it here since it is related to install and import issues.

`DEPRECATION: Legacy editable install of robocasa==0.1.0 from file:///home/ubuntu/temp_robo/robocasa (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457`

Edit:
I got it temporarily resolved by removing editable install when installing robosuite. i.e.
 "pip install -e ." got changed to  "pip install ." when installing robosuite

**Comment by snasiriany** [comment]
Interesting. I don't know of any other instances where this specific issue has occurred. We'll keep this in mind! Closing for now, if anyone else runs into this please let us know.
