### ISSUE TITLE
Is There Support for Fridge and Dishwasher Open/Close Actions and Object Placement?

### ISSUE THREAD

**Issue by ilileun** [robocasa/robocasa#76]
### Thank you for the provided code!

First of all, thank you for the amazing work on the provided code for robocasa. It's been really helpful in my current project!

---

### Question 1: Support for Fridge and Dishwasher Doors

Currently, the objects in robocasa that support opening and closing actions include the microwave and drawer. However, I would like to ask if there is support for **fridge** and **dishwasher ** in the current version.

### Question 2: Implementing Door Opening/Closing for Fridge and Dishwasher

If this feature is not currently supported, I would like to implement the functionality for these objects. Could you kindly provide some advice or recommendations on how I could approach coding the **opening and closing actions** for the fridge and dishwasher doors?

### Question 3: Object Placement Inside Fridge and Dishwasher

In addition to the door interactions, I would like to enable placing objects **inside the fridge and dishwasher**. Could you also provide guidance on how to implement this functionality?

Thank you in advance for your time and insights!

**Comment by snasiriany** [comment]
Thanks for reaching out.

Re Q1: not yet supported. Hopefully in a future release.

Re Q2: the process is a little bit involved. First, you need to take the models we provide and segment out the articulated parts, eg. the doors and racks. Then you need to model the collision geoms manually. You can see how we did this for a [microwave](https://github.com/robocasa/robocasa/blob/main/robocasa/models/assets/fixtures/microwaves/hamilton_beach/model.xml), where there are "visual" geoms corresponding to the meshes you see and "collision" geoms corresponding to the underlying geoms that participate in physics. Ten you can modify the dishwasher / fridge classes similarly using the functions we defined for [microwaves](https://github.com/robocasa/robocasa/blob/main/robocasa/models/fixtures/microwave.py).

Re Q3: you need to define the interior bounding box points of the new models, eg. like we did for the microwave [here](https://github.com/robocasa/robocasa/blob/0d34893fdaf62d2b2a112908bafa37880b4c5011/robocasa/models/assets/fixtures/microwaves/hamilton_beach/model.xml#L105-L109). You can add other custom sites for racks, placement locations, etc.

So to wrap up, take a close look at how we modeled the 3D assets and the logic for microwaves, and you can take similar steps for other fixtures.
