### ISSUE TITLE
Loading new large-scale scenes

### ISSUE THREAD

**Issue by Gary3410** [robocasa/robocasa#77]
Thank you for releasing your excellent work!
Each scene now is a single room, just like [Ai2THOR](https://github.com/allenai/ai2thor).
I would like to ask if there is any way to create large scale (e.g. 2b2b) scenes like in [ProTHOR](https://github.com/allenai/procthor).

**Comment by snasiriany** [comment]
This is on our road map. Likely will take some time as it is not an immediate focus. Thanks for understanding!
