### ISSUE TITLE
Question for the evaluation scirpt

### ISSUE THREAD

**Issue by byungokhan** [robocasa/robocasa#79]
I have a question about the evaluation script in the robomimic branch.

Looking at the code, the environment (env) is generated based on the ep_meta from the hdf5 file. When evaluating, what kind of different environment is generated compared to the training data's environment? I'm curious if only the types of objects change. Do the robot's starting pose, the kitchen layout, or the textures also change?

**Comment by snasiriany** [comment]
Great question! Compared to the training configs, we apply the following changes ontop for evaluation: https://github.com/ARISE-Initiative/robomimic/blob/0fc1329f54882cab7f65079c28881733313e717f/robomimic/scripts/config_gen/config_gen_utils.py#L108-L114

Notably:
* generative textures are turned off
* turn off randomized camera poses
* we consider 5 unique scenes, with 2 of them containing kitchen styles that are unseen
* change the object instance split from A to B, meaning we're evaluating on completely unseen object instances (but the object categories are seen)
