### ISSUE TITLE
Support for motion planning?

### ISSUE THREAD

**Issue by gadorneles** [robocasa/robocasa#89]
I would like to create my dataset using motion planning libraries with the Franka Emika Panda robot. Is there any example of something like that being used in robocasa?

**Comment by snasiriany** [comment]
We don't offer motion planning out of the box with RoboCasa, but do offer the underlying OSC / IK based controllers (courtesy RoboSuite) that can be used in to execute plans generated by a motion planner.

There has been some interest in integrating motion planning with MuJoCo (eg. [here](https://github.com/google-deepmind/mujoco/discussions/2094)). There are some tools online for this but I am not sure which one best.

If you do implement a motion planner that works for RoboCasa/RoboSuite/or even MuJoCo, please consider sharing it with us! This would be very useful to the community.

**Comment by shaoyifei96** [comment]
@gadorneles Is there an update on this? We are recently looking for the same thing, gonna integrate curobo or maybe moveit

**Comment by shaoyifei96** [comment]
No, we did get the geometry and did some local reactive obstacle avoidance, but we are not doing any global planning taking into account of all obstacles
