### ISSUE TITLE
Loading scenes from datasets such as ReplicaCAD, HSSD etc

### ISSUE THREAD

**Issue by vantony1** [robocasa/robocasa#9]
Hi there,

Thank you for sharing this work, its so well done and easy to get started.

I was wondering if there is any way to load scenes from popular household simulation datasets such as ReplicaCAD, HSSD etc to simulate tasks in different apartment setting and perhaps even multi-room settings?

**Comment by snasiriany** [comment]
Hi @vantony1, this is a great question. RoboCasa uses MuJoCo under the hood, so we would need to convert these external datasets into the MuJoCo asset format. This means converting any urdf/.navmesh formats to mjcf xml format, and all assets to obj format. It would be a somewhat involved and case-by-case operation. Thus we are leaving this most likely for a future release. In the meanwhile we welcome contributions on this front, this would be very helpful to have!
