### ISSUE TITLE
Could I use another opensource robot policy in robocasa?

### ISSUE THREAD

**Issue by xuanshao27** [robocasa/robocasa#90]
I am a newbie and want to learn more about robotics, Thank you for your contribution in this great work, I want to text some policies in robocasa, is there any doc to introduce how to train and evaluate an opensource robot policy in robocasa?

**Comment by snasiriany** [comment]
Yes! Please check out the policy learning section of our documentation: https://robocasa.ai/docs/use_cases/policy_learning.html
