### ISSUE TITLE
[Question] What is the numba package used for?

### ISSUE THREAD

**Issue by StoneT2000** [robocasa/robocasa#93]
Was just curious as I am trying to set up the environment and haven't often seen numba used with simulators before. I couldn't find any reference to `numba` in this repo so wasn't sure.

**Comment by snasiriany** [comment]
It's used in robosuite. Eg. here: https://github.com/ARISE-Initiative/robosuite/blob/f966f87ef3eef29cc57b365aae248827fca0e543/robosuite/utils/transform_utils.py#L11

It's used to speed up some of the computations for the controllers.

Let us know if you have any additional questions!
